name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
          pip3 install --upgrade buildozer cython
          
          # 1. Запускаємо buildozer перший раз, щоб він створив структуру папок
          # Ми очікуємо помилку, тому ігноруємо її через || true
          buildozer android debug || true
          
          # 2. Тепер, коли папки створені, приймаємо ліцензії (якщо sdkmanager існує)
          SDKMGR=$(find /home/runner/.buildozer/ -name "sdkmanager" | head -n 1)
          if [ -f "$SDKMGR" ]; then
            yes | $SDKMGR --licenses || true
          fi
          
          # 3. Фінальна збірка
          buildozer -v android debug
